
# dataset info
dataset_path: "/srv/home/sonic/FUnIE-GAN/PyTorch/uporp/data/euvp/"

# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 1 # epochs
ckpt_interval: 20  # epochs



 
